### PR TITLE
Redesign footer according de data of issue-393

### LINKED ISSUE #393: (HTML/CSS) redesign of footer to follow this screenshot
Let's change the footer from this:
screen shot 2016-10-29 at 12 12 34 pm

... to THIS:
screen shot 2016-10-29 at 1 09 12 pm

Two changes to the screenshot above:
- remove the ___ border at the bottom
- The grid layout should be 6-2-2-2, not 3-2-2-5 as shown above.
- Add a "Built By Cool People Around The World!" below the "Help sponsor us!" text

If you'd like to take this bug, PLEASE leave a comment in the thread to claim it.

And be sure to read our [contributing.md](https://github.com/codebuddiesdotorg/cb-v2-scratch/blob/master/contributing.md) docs!

(cc @stratosgear and @bennycarlsson in case you're interested)

### PR DESCRIPTION
**Pull request by garri-ribeiro**
Fix #393 

Hello ! I redesign the footer to website.

footer

### CODE REVIEW

**Comment by adachiu** [comment]
@garri-ribeiro ah, you misread the instructions:

`The grid layout should be 6-2-2-2, not 3-2-2-5 as shown above.`

You made it 3-2-2-5. It should be 6-2-2-2. Can you commit the fix? Thanks!

**Comment by garri-ribeiro** [comment]
aahh ok, i'll commit this o/

**Comment by garri-ribeiro** [comment]
I change grid and commit :) , sorry to misinterpret

**Comment by adachiu** [comment]
Thanks!

**Comment by adachiu** [comment]
@garri-ribeiro One more request. The `sponsor us` column looks squished after we changed it. I just played with `5-2-2-3` and it solves the width issue. Do you mind editing it to `5-2-2-3` ? 

It would look like this:
screen shot 2016-10-29 at 6 09 57 pm

If you have time, could you also add media queries to `_footer.scss`

The following within `.footer-social`

>  @include breakpoint(tiny) { margin: 30px 0; }
    @include breakpoint(xsmall) { margin: 30px 0; }
    @include breakpoint(small) { margin: 0 0 30px; }
    @include breakpoint(xmedium) { margin: 0 0 30px; }

The result should look like this when the browser is scaled down:
screen shot 2016-10-29 at 6 27 11 pm

Many thanks

**Comment by garri-ribeiro** [comment]
Hey, I fix this, but I changed margin of size small and xmedium for this, because browser resize these elements of the footer 
```
    @include breakpoint(tiny) { margin: 30px 0; }
    @include breakpoint(xsmall) { margin: 30px 0; }
    @include breakpoint(small) { margin: 30px 0 30px; }
    @include breakpoint(xmedium) { margin: 30px 0 30px; }
```

**Comment by lpatmo** [comment]
Looks awesome! Thank you @garri-ribeiro for fixing the issue and @adachiu for reviewing!

**Pull request merged**
