### PR TITLE
Added character count on status

### PR DESCRIPTION
**Pull request by JelaniThompson**
Some of these changes happened solely because I ran `meteor update` so a lot of the version numbers have been changed. I was only doing work in update-status.html/update-status.js and my changes are functional.

### CODE REVIEW

**Comment by William-R-Wilson** [comment]
Hi Jelani, thanks for this.  How hard would it be to resubmit this without the updates?  I think meteor 1.4 will break some packages.

**Comment by JelaniThompson** [comment]
@William-R-Wilson Oh, did you mean reverting with something like this? http://stackoverflow.com/questions/15465018/can-i-undo-updating-meteor

**Comment by William-R-Wilson** [comment]
Maybe a `git revert`, then a new commit with only the files you wanted?  I think you can do `git commit add file.html file.js` and send in a new PR.  I'm @will on slack if you want to chat over there.

**Comment by will** [comment]
I'm @will on github, if you want to chat over here

**Comment by William-R-Wilson** [comment]
I can merge this but!  I'm getting this exception on my local machine, master branch (before pulling this branch):  

```Exception in template helper: getDate@http://localhost:3000/app/app.js?hash=cf8b18a7060ce9480a29510dff81228ea5dcf5a3:3349:90
bindDataContext/<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2994:14
Blaze._wrapCatchingExceptions/<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1653:14
wrapHelper/</<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3046:14
Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12
wrapHelper/<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3045:12
Spacebars.call@http://localhost:3000/packages/spacebars.js?hash=65db8b6a8e3fca189b416de702967b1cb83d57d5:172:12
Spacebars.mustacheImpl@http://localhost:3000/packages/spacebars.js?hash=65db8b6a8e3fca189b416de702967b1cb83d57d5:106:10
Spacebars.mustache@http://localhost:3000/packages/spacebars.js?hash=65db8b6a8e3fca189b416de702967b1cb83d57d5:110:16
require<.client.templates.hangout["template.hangout-item.js"]/Template.hangoutItem</<@http://localhost:3000/app/app.js?hash=cf8b18a7060ce9480a29510dff81228ea5dcf5a3:2550:12
doRender@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2027:20
viewAutorun/</<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1875:18
Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12
viewAutorun/<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1873:14
Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2214:12
viewAutorun@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1872:12
Tracker.Computation.prototype._compute@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:351:5
Tracker.Computation@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:239:5
Tracker.autorun@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:590:11
Blaze.View.prototype.autorun@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1885:14
Blaze._materializeView/<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2021:5
Tracker.nonreactive@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:617:12
Blaze._materializeView@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2020:3
materializeDOMInner@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1476:9
Blaze._materializeDOM@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1418:3
Blaze._materializeDOM@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1427:7
doMaterialize@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2033:32
Tracker.nonreactive@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:617:12
doRender@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2031:9
viewAutorun/</<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1875:18
Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:3687:12
viewAutorun/<@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1873:14
Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:2214:12
viewAutorun@http://localhost:3000/packages/blaze.js?hash=ef41aed769a8945fc99ac4954e8c9ec157a88cea:1872:12
Tracker.Computation.prototype._compute@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:351:5
Tracker.Computation.prototype._recompute@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:370:9
Tracker._runFlush@http://localhost:3000/packages/tracker.js?hash=6f5d0f5486aaa54b0abe636174eeb06dcc2a736b:509:9
onGlobalMessage@http://localhost:3000/packages/meteor.js?hash=ae8b8affa9680bf9720bd8f7fa112f13a62f71c3:401:11```

Don't want to merge any of my funky settings into master and introduce a new bug.

**Pull request closed without merging**
