### PR TITLE
Issue 7 create a hangout

### PR DESCRIPTION
**Pull request by lpatmo**

### CODE REVIEW

**Comment by lpatmo** [comment]
Note to self: had to do `git pull heroku issue-7-create-a-hangout` before `git push heroku issue-7-create-a-hangout:master`

**Comment by sergeant-q** [comment]
What is the expected behavior here? Just provide the google hangout button? How do we share or attach the hangout URL to the db document?

**Comment by lpatmo** [comment]
@sergeant-q Christoph and I went through this in the hangout today. The google hangout app posts the hangout URL and post ID back to the cbv2 app:

```
function init() { // When API is ready... 
        gapi.hangout.onApiReady.add( function(eventObj) {
           if (eventObj.isApiReady) { 
            document.getElementById('showParticipants') .style.visibility = 'visible';
            registerHangout();
           } 
          }); 
        
      } // Wait for gadget to load. 


        function registerHangout() {
          var hangoutUrl = gapi.hangout.getHangoutUrl();
          var startData = gapi.hangout.getStartData();
          var callbackUrl = 'http://cbv2-staging.herokuapp.com/hangout/'+startData;

            $.ajax({
              type: "PUT",
              url: callbackUrl,
              success: successFunc,
              dataType: 'json',
              data: {
                      "hangoutUrl": hangoutUrl,
                      "startData": startData
                     }
            });
        }
```

And on server/routes.js on the cbv2 app, we have:

```
var bodyParser = require('body-parser');

Picker.middleware(bodyParser.json());

Picker.route('/hangout/:_id', function(params, req, res) {
	//add in some checking ot make sure re.body.hangoutUrl is a hangout URL	
  Hangouts.update(params._id, { $set: { url: req.body.hangoutUrl }}, function(err, result){ 
  	if (err) {
  		res.statusCode = 404;
  	} else {
  		res.statusCode = 200;
  	}
  	res.end();
  });
});
```

So this'll update the schema for the hangout by adding a "url" key:

```
 "reminder_sent": false,
  "timestamp": "2016-05-18T02:38:41.655Z",
  "views": 3,
  "url": "https://talkgadget.google.com... etc."
}
```

**Comment by sergeant-q** [comment]
Gotcha so this might be on a new hangout created because I didn't see the url property in the schema when I updated the start time for an _existing_ (old) hangout.

**Comment by lpatmo** [comment]
The XML app is now hosted on the staging site: https://cbv2-staging.herokuapp.com/app.xml

**Pull request merged**
