### PR TITLE
Feature 49 email reminders

### PR DESCRIPTION
**Pull request by sergeant-q**
I currently have the cron job interval set to _every 5 mins_ for **testing purposes** only. Please test various scenarios to see if it works as intended. Once I get code review approval, I can commit an update to set it to _every hour_ and then merge the PR. 

**The logic is as follows:**

- Timezone is coerced to PT for baseline and consistency
- If hangout is starting within two hours or less - a Slack notification will be sent (no email reminder)
- if hangout is starting within 24 hours - an email will be fired off to all participants who RSVP'd (no slack notification)

**Email Reminder:**

screen shot 2016-04-12 at 11 56 00 pm

**Slack Notification:**

screen shot 2016-04-12 at 11 57 14 pm

### CODE REVIEW

**Comment by lpatmo** [comment]
W0000t!!! Thank you, @sergeant-q!

Two small wording-related things: 
- In the email template, can we add "Please update your RSVP if you can't make the hangout anymore."
- In the Slack alert, change to "is set to start in less than two hours!" (or alternatively: "is set to start in two hours or fewer").

**Comment by sergeant-q** [comment]
@lpatmo sounds good! I think I need to do one more logic check.  It may require some additional work now that I think about it. Went to bed late last night so I woke up thinking about it! lol

Standby until I get a chance to look at it.

**Comment by sergeant-q** [comment]
@lpatmo I fixed the verbiage on the slack alert and email reminder.  I also fixed the logic to ensure we search for and act upon only those hangouts that a reminder has _not_ been sent out for.

**Comment by lpatmo** [comment]
Found two bugs! :)

a) When a hangout is copied, the reminder email can't get the username and calls it @undefined
b) Description containing a URL has an extra _

**Comment by sergeant-q** [comment]
@lpatmo I believe this commit https://github.com/codebuddiesdotorg/cb-v2-scratch/pull/107/commits/97b9fefe3c6d74fe905be1c107b8693d9974eaaa should fix the reminders not firing off for cloned hangouts.  Please test and let me know!

**Pull request merged**
