### PR TITLE
Issue 322 faq update

### LINKED ISSUE #322: FAQ UI Update
I'm updating the layout of the FAQ page to better utilize the space.

Also, working on creating a subtle background illustration for the header. I'll post here for reviews.

Currently everything's crammed to one side.
screen shot 2016-10-10 at 10 37 52 pm

### PR DESCRIPTION
**Pull request by adachiu**
Updated the FAQ page layout and content.

Also, attempted to clean up the code indentations. Please let me know if there's anything else I can do to make it better. Thanks!

Closes #322

### CODE REVIEW

**Comment by lpatmo** [comment]
One question, @adachiu -- I noticed in this PR and in the update for the `About` page the background on the home page is gone. I take it it's intentional, but just wanted to confirm. Thanks!

**Comment by adachiu** [comment]
@lpatmo 
Reasons:
- if I remember correctly, when I was updating the header, the home bg image was also shown on About and FAQ so I deleted it
- since the new home logged-in view (cards design) does not have the bg image, we should remove it from the home page as well in order to maintain consistency. We could use the new gradient header bg on the home page (behind the slack window in header). I'll look into it.

**Comment by adachiu** [comment]
@lpatmo RE background, I've added one more commit to #336 to add back a blue background so that `home-logged-in` doesn't have a white background.

**Comment by lpatmo** [comment]
Merged! Thanks @adachiu!

**Pull request merged**
