### PR TITLE
#132 New schema reworking 

### PR DESCRIPTION
**Pull request by distalx**
**change log** #132 
users schema
hangouts schema
refactor and dead code removal 
**bugfix**
clone hangout date-time-picker. &
#154.

### CODE REVIEW

**Comment by sergeant-q** [comment]
I wanted to wait until this branch was merged in order to work on issue #147 since I noticed you modified the profile html/js files.  I pulled in this branch to test and I am unable to create a new hangout.

console error shows an issue on line number `53` in the **/client/templates/hangout/hangout-item.js file**. Particularly with unable to find the length of undefined property for `hangout.attendees.length`. 

@distalx I think you modified the schema for hangouts correct? I think this is looking for something else now right?

**Comment by sergeant-q** [comment]
@distalx here's more details on the error I see on the console:

`Exception while invoking method 'createHangout' TypeError: Cannot read property 'default' of undefined
I20160720-15:57:12.255(-7)?     at [object Object].createHangout (server/hangouts/methods.js:26:17)`

**Comment by distalx** [comment]
@sergeant-q it seems like in your db you have some data with the old schema - so if run `meteor reset` it will clear you database for you - and your won't have any issues.

**Comment by lpatmo** [comment]
@distalx Thanks for this and for pushing to the cbv2-staging.herokuapp.com site! I just noticed that editing a hangout isn't working.

**Comment by distalx** [comment]
@lpatmo fixed and redeployed !

**Pull request merged**
