### PR TITLE
Enhancement#114

### PR DESCRIPTION
**Pull request by distalx**
#114 

- [ ] storing search terms.
- [x] view counts for each hangouts.
- [x] 	line breaks.
- [x] 	rsvp notifications

Also,

- fixed the broken logo link [footer]
- fixed user profile link [status]
- fixed user profile link [learning]
- added force-ssl.

### CODE REVIEW

**Comment by sergeant-q** [comment]
Some minor cosmetic issue I discovered (css).  Footer doesn't seem to align with the header.  Needs to have some containment. 

image

**Comment by sergeant-q** [comment]
Another possible CSS issue is the **hangouts completed** list on the profile page. The hangout titles seem to be getting cut off.  

image

Any reason why we have scrolling enabled for the hangouts themselves?

**Comment by sergeant-q** [comment]
**_Remove RSVP_** link does not work in the hangout details page:

image

Expected behavior is to inform me I cannot remove myself from the hangout since I am the creator.  However nothing happens when I click on it.

**Comment by lpatmo** [comment]
Footer fix <--- assigned myself.

**Comment by lpatmo** [comment]
Fixed footer and view on the profile page! @distalx fixed the other stuff.

I think this branch is ready to merge. Can folks volunteer to `git pull` and check it over?

**Comment by sergeant-q** [comment]
Looks good!

**Comment by lpatmo** [comment]
Thanks @sergeant-q! I am going to merge this in.

**Pull request merged**
